language: python
python:
  - "3.7"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --user codecov
# command to run tests
env:
  - CODECOV_TOKEN="cd055358-17dd-47cf-84cd-a378bbd4d45f"
script:
  - pytest
after_success:
  - codecov
